name: Deploy Data Platform to Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENVIRONMENT: develop
          PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          cdk deploy "*" --require-aproval never
